# -*- coding: utf-8 -*-
"""Day1 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KCGw_7GR9V07gbqmlBSKabG1IL6UHJPC
"""

x = int (input('Enter first number: '))
y = int (input('Enter second number: '))
print (pow(x,y))

list1 = [33,9,6,5,8,2,12,10,15,199]
for i in list1:
 if (i % 3 == 0):
  print(i)